name : Deployment

on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write

env:
  CONTAINER_REGISTRY: ghcr.io
  TF_DIRECTORY: infrastructure/terraform
  TARGET_IMAGE_TAG: ghcr.io/${{ github.repository }}:0.0.${{ github.run_id }}
  DEFAULT_IMAGE_TAG: ghcr.io/${{ github.repository }}:latest

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          .github
          src
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/src
        push: true
        tags: |
          ${{ env.TARGET_IMAGE_TAG }}
          ${{ env.DEFAULT_IMAGE_TAG }}
  update-infrastructure:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_environment_short: ${{ vars.ENVIRONMENT_SHORT }}
      TF_VAR_docker_registry_url: 'https://ghcr.io'
      TF_VAR_docker_registry_username: ${{ github.repository_owner }}
      TF_VAR_docker_registry_password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}
      TF_VAR_default_docker_image_name: ghcr.io/${{ github.repository }}:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Terraform init
      working-directory: ${{ env.TF_DIRECTORY }}
      shell: pwsh
      run: terraform init -backend-config="resource_group_name=${{ vars.TF_STATE_RESOURCE_GROUP_NAME }}" -backend-config="storage_account_name=${{ vars.TF_STATE_STORAGE_ACCOUNT_NAME }}"
    - name: Terraform plan
      working-directory: ${{ env.TF_DIRECTORY }}
      shell: pwsh
      run: terraform plan -input=false -var-file="${{ github.workspace}}/infrastructure/deployments/${{ vars.ENVIRONMENT_SHORT }}/.tfvars" -out="tfplan"
    - name: Terraform apply
      working-directory: ${{ env.TF_DIRECTORY }}
      shell: pwsh
      run: terraform apply -auto-approve -input=false tfplan
  deploy-app:
    needs: [build,update-infrastructure]
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Install EF Core tools
      run: dotnet tool install --global dotnet-ef
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run migrations
      env:
        ConnectionStrings__MealmapDb: "Server=sql-mealmap-prod.database.windows.net; Authentication=Active Directory Service Principal; Encrypt=True; Database=sqldb-mealmap-prod; User Id=${{ vars.ARM_CLIENT_ID }}; Password=${{ secrets.ARM_CLIENT_SECRET }}"
      working-directory: src/Mealmap.Migrations
      run: dotnet ef database update
    - name: Deploy app
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-mealmap-prod
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.TARGET_IMAGE_TAG }}
