name: Integration

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Terraform format
      working-directory: infrastructure/terraform
      shell: pwsh
      run: terraform fmt -check
    - name: Terraform init
      working-directory: infrastructure/terraform
      shell: pwsh
      run: terraform init -backend=false
    - name: Terraform validate
      working-directory: infrastructure/terraform
      shell: pwsh
      run: terraform validate
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore Node env
      working-directory: src/Mealmap.Web
      run: npm install
    - name: Angular Unit Tests
      working-directory: src/Mealmap.Web
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName~UnitTests"
    - name: Spin up database
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=MealIntTest!" -p 5001:1433 --name mealmapsql --hostname mealmapsql -d mcr.microsoft.com/mssql/server:2022-latest
    - name: Infrastructure Integration Tests
      working-directory: tests/Mealmap.Infrastructure.IntegrationTests
      run: dotnet test --no-build --verbosity normal
    - name: API Integration Tests
      working-directory: tests/Mealmap.Mealmap.Api.IntegrationTests
      run: dotnet test --no-build --verbosity normal
