name: Integration

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Terraform format
      working-directory: infrastructure/terraform
      shell: pwsh
      run: terraform fmt -check
    - name: Terraform init
      working-directory: infrastructure/terraform
      shell: pwsh
      run: terraform init -backend=false
    - name: Terraform validate
      working-directory: infrastructure/terraform
      shell: pwsh
      run: terraform validate
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "FullyQualifiedName!~Mealmap.Infrastructure.IntegrationTests"
  # integration-test:
  #   needs: [lint, unit-test]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
